### ISSUE TITLE
What would be the workflow for working with full hd images.

### ISSUE THREAD

**Issue by larsvankleef** [kornrunner/php-blurhash#3]
My php code crashes when i want to upload images that are bigger then example images. The memory got filled up to the max when analyzing all the pixels in the images. 
```
$row[] = [$colors['red'], $colors['green'], $colors['blue']];
```
Looks like this array got to big when using a image that is like 1920 x 1080. What would you recommend?

**Comment by nebkam** [comment]
Have you tried raising the memory_limit in php.ini?
If that's not available, maybe resize image before hashing?

**Comment by nour-majed** [comment]
I also have this issue and it's not about raising the memory_limit in php.ini because it's still taking too much time

**Comment by DagAgren** [comment]
Resize the image to something around 32x32 before encoding.
