### ISSUE TITLE
Decoder produces pixels with color component value = 256

### ISSUE THREAD

**Issue by ingria** [kornrunner/php-blurhash#7]
This causes `imagecolorallocate` to fail (X component is out of range).

For example, check this blurhash: `LES6SutTOH.T_Nx[$wwGD+IVT1kr`

Not sure if there's a bug in decoder, or we should just use `min(255, $value)` in `imagecolorallocate`.

**Comment by kornrunner** [comment]
What are the image dimensions? Could you please provide the original image as well? Thank you.

**Comment by ingria** [comment]
Original image is 800x1673 (zipped to avoid Github's compression): [example.zip](https://github.com/kornrunner/php-blurhash/files/5826357/example.zip)

I fit it to 32x32 before creating blurhash. X component is 4, Y is 3.

**Comment by kornrunner** [comment]
Algorithm is on pair with other implementations, this is a fringe case with PHP and floating point. I've limited the values in `Color` class so this should no longer be an issue. Thanks for reporting.
